export const STREAM = {
	ANY: 'STREAM.ANY',
	CONTAINER: 'STREAM.CONTAINER',
}

export const TEXT = {
	ANY: 'TEXT.ANY',
	ATOM: 'TEXT.ATOM',
	WORD: 'TEXT.WORD',
	SENTENCE: 'TEXT.SENTENCE',
	BLOB: 'TEXT.BLOB',
}
